name: Continuous Integration (STAC Validation)

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - master

env:
  # Global environment variable
  IMAGE: qgis/qgis
  WITH_PYTHON_PEP: "true"
  MUTE_LOGS: "true"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Running tests on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install plugin dependencies
        run: pip install -r requirements.txt

      - name: Run STAC validator
        run: |
          python src/main.py
          stac-validator catalog/catalog.json